project:
  type: website

website:
  title: "Airline Performance Analysis"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: story.qmd
        text: "Story"

format:
  html:
    theme: cosmo
    toc: true





